'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {ServiceProjectStore}=require('../src/services/project/ServiceProjectStore');
const core=require('../src/services/community/HeritageServiceDocument');
const {CommunityPlannerCache}=require('../src/services/community/CommunityPlannerCache');
const {bundledPlannerResponse}=require('../src/services/community/BundledPlannerEditor');
test('Adjust pins the active local revision, preserves its draft after restart, and fetches resources only on request',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'active-adjust-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
  const store=new ServiceProjectStore({rootPath:path.join(root,'projects')});
  const {project}=await store.create({id:'active',title:'Active show',serviceDate:'2026-10-04',profileId:'main-sanctuary'});
  const validated=core.validateHeritageServiceDocumentSource(core.serializeHeritageServiceDocument(core.createHeritageServiceDocument(project)));
  const envelope={...validated,syncId:'active',syncVersion:7,status:'ready',changedAt:project.updatedAt};
  const reads=[],writes=[];
  const fetch=async request=>{if(request.method==='GET'){reads.push(request.url);return new Response(JSON.stringify({items:[]}));}writes.push(request.url);return new Response('{}',{status:503});};
  const options={rootPath:path.join(root,'adjust'),origin:'https://heritage.test',fetch,backgroundSync:true};
  const cache=new CommunityPlannerCache(options);await cache.pinActiveShow(envelope,{revision:envelope.revision,syncVersion:7});
  const endpoint='https://heritage.test/api/community/service-documents';
  assert.equal((await (await cache.request(new Request(endpoint+'/active'))).json()).serviceDocument.project.title,'Active show');
  await cache.request(new Request(endpoint));
  await cache.request(new Request(endpoint+'/active/history'));
  assert.deepEqual(reads,[]);
  const edited=structuredClone(project);edited.title='Quick local fix';edited.revision++;
  const source=core.serializeHeritageServiceDocument(core.createHeritageServiceDocument(edited));
  const saved=await cache.request(new Request(endpoint+'/active',{method:'PUT',body:JSON.stringify({schemaVersion:1,syncId:'active',baseRevision:envelope.revision,baseSyncVersion:7,documentSource:source,status:'ready',saveKind:'manual',requestId:'local-edit'})}));
  assert.equal(saved.status,200);assert.equal((await saved.json()).serviceDocument.project.title,'Quick local fix');
  await cache.syncQueue;
  const restarted=new CommunityPlannerCache(options);await restarted.pinActiveShow(envelope,{revision:envelope.revision,syncVersion:7});
  assert.equal(restarted.envelope('active').project.title,'Quick local fix');
  assert.equal(restarted.envelope('active').pending,true);
  assert.equal((await restarted.request(new Request(endpoint+'/other'))).status,409);
  await restarted.request(new Request(endpoint+'/library/songs'));
  assert.equal(reads.length,1);assert.match(reads[0],/library\/songs$/);
});
test('the bundled editor loads locally, localizes its shell, and rejects path escapes',async()=>{
  const rootPath=path.resolve(__dirname,'../assets/planner-editor');
  const html=await bundledPlannerResponse(new Request('https://heritage.test/syncshow-local/adjust/index.html?service=active'),{rootPath,language:'ru'});
  assert.equal(html.status,200);assert.match(await html.text(),/<html lang="ru">/);
  const escaped=await bundledPlannerResponse(new Request('https://heritage.test/syncshow-local/adjust/%2e%2e%2fpackage.json.js'),{rootPath});
  assert.equal(escaped.status,404);
});
